#!/bin/sh

touch /var/lib/suricata/alerts/alerts.json.new
mv /var/lib/suricata/alerts/alerts.json.new /var/lib/suricata/alerts/alerts.json

# PID 1 will always be suricata in this container
/bin/kill -HUP 1
